In [2]:
import pandas as pd
import numpy as np

## Data from the EIA: Captive hydrogen production at refineries

In [17]:
eia_df = pd.read_excel('./hydrogen_production_capacities_at_US_refineries_EIA_2022.xlsx', skiprows=3,header=0)
eia_df = eia_df.iloc[:-2,:] # Remove totals
eia_df = eia_df[['State', 'Company', 'City', 2022]] # Only keep data for year 2022
eia_df.dropna(axis=0, ignore_index=True, inplace=True) # Drop rows with null production 
eia_df

            State                               Company            City   2022
0         ALABAMA                      HUNT REFINING CO      TUSCALOOSA   40.0
1          ALASKA             TESORO ALASKA COMPANY LLC           KENAI   13.0
2        ARKANSAS    CROSS OIL REFINING & MARKETING INC       SMACKOVER    3.0
3        ARKANSAS                           LION OIL CO       EL DORADO   10.0
4      CALIFORNIA                       CHEVRON USA INC        RICHMOND  330.0
5      CALIFORNIA                       CHEVRON USA INC      EL SEGUNDO   74.0
6      CALIFORNIA                   PHILLIPS 66 COMPANY           RODEO   22.0
7      CALIFORNIA                   PHILLIPS 66 COMPANY      WILMINGTON  105.0
8      CALIFORNIA           SAN JOAQUIN REFINING CO INC     BAKERSFIELD    4.0
9      CALIFORNIA              MARTINEZ REFINING CO LLC        MARTINEZ  179.0
10     CALIFORNIA        TESORO REFINING & MARKETING CO          CARSON  120.0
11     CALIFORNIA         VALERO REFINING CO CALIFORNIA         BENICIA  135.0
12       COLORADO               SUNCOR ENERGY (USA) INC   COMMERCE CITY   22.0
13       DELAWARE         DELAWARE CITY REFINING CO LLC   DELAWARE CITY   65.0
14         HAWAII               PAR HAWAII REFINING LLC         KAPOLEI   18.0
15       ILLINOIS              PDV Midwest Refining LLC          LEMONT   12.0
16       ILLINOIS                       WRB REFINING LP      WOOD RIVER  190.0
17         KANSAS            CHS MCPHERSON REFINERY INC       MCPHERSON   42.0
18         KANSAS      COFFEYVILLE RESOURCES RFG & MKTG     COFFEYVILLE   22.0
19         KANSAS  HOLLYFRONTIER EL DORADO REFINING LLC       EL DORADO   56.0
20      LOUISIANA    CALUMET COTTON VALLEY REFINING LLC   COTTON VALLEY    2.0
21      LOUISIANA        CALUMET PRINCETON REFINING LLC       PRINCETON    4.0
22      LOUISIANA       CALUMET SHREVEPORT REFINING LLC      SHREVEPORT   12.0
23      LOUISIANA       VALERO REFINING NEW ORLEANS LLC           NORCO  100.0
24      MINNESOTA              Flint Hills Resources LP      SAINT PAUL  199.0
25      MINNESOTA          ST PAUL PARK REFINING CO LLC     SAINT PAUL    10.0
26    MISSISSIPPI                       CHEVRON USA INC      PASCAGOULA  229.0
27    MISSISSIPPI                    ERGON REFINING INC       VICKSBURG   13.0
28        MONTANA          CALUMET MONTANA REFINING LLC     GREAT FALLS   20.0
29        MONTANA             Cenex Harvest States Coop          LAUREL   70.0
30        MONTANA       EXXONMOBIL REFINING & SUPPLY CO        BILLINGS   23.0
31        MONTANA                   PHILLIPS 66 COMPANY        BILLINGS   36.0
32     NEW JERSEY             PAULSBORO REFINING CO LLC       PAULSBORO    9.0
33     NEW JERSEY                   PHILLIPS 66 COMPANY          LINDEN   22.0
34     NEW MEXICO         HOLLYFRONTIER NAVAJO REFINING         ARTESIA   38.0
35       OKLAHOMA                   PHILLIPS 66 COMPANY      PONCA CITY   35.0
36       OKLAHOMA           VALERO REFINING CO OKLAHOMA         ARDMORE   27.0
37       OKLAHOMA                 WYNNEWOOD REFINING CO       WYNNEWOOD   10.0
38   PENNSYLVANIA                       UNITED REFINING          WARREN   10.0
39      TENNESSEE      VALERO REF COMPANY TENNESSEE LLC         MEMPHIS   30.0
40          TEXAS                                VALERO  CORPUS CHRISTI  160.0
41          TEXAS       DIAMOND SHAMROCK REFINING CO LP          SUNRAY   30.0
42          TEXAS                     WESTERN REFINING          EL PASO   10.0
43          TEXAS                          WRB REFINING          BORGER   91.0
44     WASHINGTON            BP West Coast Products LLC        FERNDALE  186.0
45  WEST VIRGINIA               ERGON WEST VIRGINIA INC          NEWELL    3.0
46        WYOMING          SINCLAIR WYOMING REFINING CO        SINCLAIR   52.0

## Convert to hydrogen demand in kg/day
### Original data in million standard cubic feet per day

In [19]:
hydrogen_density = 0.00241 # kg/ standard cubic feet
clean_df = eia_df[['State', 'Company','City']]
clean_df['2022'] = eia_df[2022]*1e6*hydrogen_density
clean_df

,State,Company,City,2022
0,ALABAMA,HUNT REFINING CO,TUSCALOOSA,96400.0
1,ALASKA,TESORO ALASKA COMPANY LLC,KENAI,31330.0
2,ARKANSAS,CROSS OIL REFINING & MARKETING INC,SMACKOVER,7230.0
3,ARKANSAS,LION OIL CO,EL DORADO,24100.0
4,CALIFORNIA,CHEVRON USA INC,RICHMOND,795300.0
5,CALIFORNIA,CHEVRON USA INC,EL SEGUNDO,178340.0
6,CALIFORNIA,PHILLIPS 66 COMPANY,RODEO,53020.0
7,CALIFORNIA,PHILLIPS 66 COMPANY,WILMINGTON,253050.0
8,CALIFORNIA,SAN JOAQUIN REFINING CO INC,BAKERSFIELD,9640.0
9,CALIFORNIA,MARTINEZ REFINING CO LLC,MARTINEZ,431390.0
10,CALIFORNIA,TESORO REFINING & MARKETING CO,CARSON,289200.0
11,CALIFORNIA,VALERO REFINING CO CALIFORNIA,BENICIA,325350.0
12,COLORADO,SUNCOR ENERGY (USA) INC,COMMERCE CITY,53020.0
13,DELAWARE,DELAWARE CITY REFINING CO LLC,DELAWARE CITY,156650.0
14,HAWAII,PAR HAWAII REFINING LLC,KAPOLEI,43380.0
15,ILLINOIS,PDV Midwest Refining LLC,LEMONT,28920.0
16,ILLINOIS,WRB REFINING LP,WOOD RIVER,457900.0
17,KANSAS,CHS MCPHERSON REFINERY INC,MCPHERSON,101220.0
18,KANSAS,COFFEYVILLE RESOURCES RFG & MKTG,COFFEYVILLE,53020.0
19,KANSAS,HOLLYFRONTIER EL DORADO REFINING LLC,EL DORADO,134960.0
20,LOUISIANA,CALUMET COTTON VALLEY REFINING LLC,COTTON VALLEY,4820.0
21,LOUISIANA,CALUMET PRINCETON REFINING LLC,PRINCETON,9640.0
22,LOUISIANA,CALUMET SHREVEPORT REFINING LLC,SHREVEPORT,28920.0
23,LOUISIANA,VALERO REFINING NEW ORLEANS LLC,NORCO,241000.0
24,MINNESOTA,Flint Hills Resources LP,SAINT PAUL,479590.0
25,MINNESOTA,ST PAUL PARK REFINING CO LLC,SAINT PAUL,24100.0
26,MISSISSIPPI,CHEVRON USA INC,PASCAGOULA,551890.0
27,MISSISSIPPI,ERGON REFINING INC,VICKSBURG,31330.0
28,MONTANA,CALUMET MONTANA REFINING LLC,GREAT FALLS,48200.0
29,MONTANA,Cenex Harvest States Coop,LAUREL,168700.0
30,MONTANA,EXXONMOBIL REFINING & SUPPLY CO,BILLINGS,55430.0
31,MONTANA,PHILLIPS 66 COMPANY,BILLINGS,86760.0
32,NEW JERSEY,PAULSBORO REFINING CO LLC,PAULSBORO,21690.0
33,NEW JERSEY,PHILLIPS 66 COMPANY,LINDEN,53020.0
34,NEW MEXICO,HOLLYFRONTIER NAVAJO REFINING,ARTESIA,91580.0
35,OKLAHOMA,PHILLIPS 66 COMPANY,PONCA CITY,84350.0
36,OKLAHOMA,VALERO REFINING CO OKLAHOMA,ARDMORE,65070.0
37,OKLAHOMA,WYNNEWOOD REFINING CO,WYNNEWOOD,24100.0
38,PENNSYLVANIA,UNITED REFINING,WARREN,24100.0
39,TENNESSEE,VALERO REF COMPANY TENNESSEE LLC,MEMPHIS,72300.0
40,TEXAS,VALERO,CORPUS CHRISTI,385600.0
41,TEXAS,DIAMOND SHAMROCK REFINING CO LP,SUNRAY,72300.0
42,TEXAS,WESTERN REFINING,EL PASO,24100.0
43,TEXAS,WRB REFINING,BORGER,219310.0
44,WASHINGTON,BP West Coast Products LLC,FERNDALE,448260.0
45,WEST VIRGINIA,ERGON WEST VIRGINIA INC,NEWELL,7230.0
46,WYOMING,SINCLAIR WYOMING REFINING CO,SINCLAIR,125320.0

In [20]:
# Save results for use in code
clean_df.to_csv('../h2_demand_refineries.csv')

## Check natural gas consumption and equivalent natural gas demand

In [25]:
# Map each refinery to corresponding padd
map_padd = pd.read_excel('./map_state_padd.xlsx', skiprows=1)
refineries_mapped = pd.merge(clean_df, map_padd, on='State')
refineries_mapped.head(3)

      State                             Company        City     2022  PADD
0   ALABAMA                    HUNT REFINING CO  TUSCALOOSA  96400.0     3
1    ALASKA           TESORO ALASKA COMPANY LLC       KENAI  31330.0     5
2  ARKANSAS  CROSS OIL REFINING & MARKETING INC   SMACKOVER   7230.0     3

In [27]:
# Sum of hydrogen demand per padd
sum_ref_padd = refineries_mapped.groupby('PADD').sum('2022')
# and convert to equivalent natural gas demand in MMCf
# from H2A tool 0.1578 MMBtu/kgH2
h2_to_ng_smr = 0.1578 #MMBtu NG/kgH2
# NG: 1 Mcf = 1.038 MMBtu
vol_to_nrj_ng = 1038 # MMBtu/MMcf
sum_ref_padd['NG eq demand 2022(MMcf/year)'] = 365*sum_ref_padd['2022']*h2_to_ng_smr/vol_to_nrj_ng
sum_ref_padd

           2022  NG eq demand 2022(MMcf/year)
PADD
1      262690.0                  14576.258121
2     1525530.0                  84649.278815
3     1788220.0                  99225.536936
4      537430.0                  29821.151936
5     2858260.0                 158600.386532

In [40]:
# Load data natural gas feedstock for h2 production at refineries
published_ng_feedstock_padd = pd.read_excel('./nat_gas_feedstock_h2_prod_refineries_padd_level_eia.xls', sheet_name='Data 1', skiprows=2)
published_ng_feedstock_padd = published_ng_feedstock_padd.iloc[-1, 2:]
published_ng_feedstock_padd = published_ng_feedstock_padd.to_frame()
published_ng_feedstock_padd.set_index(pd.Series([1,2,3,4,5]),inplace=True)
published_ng_feedstock_padd.rename(columns={14:'Published NG Feedstock (MMcf/year)'}, inplace=True)
published_ng_feedstock_padd.reset_index(names=['PADD'], inplace=True)
published_ng_feedstock_padd

   PADD Published NG Feedstock (MMcf/year)
0     1                               6202
1     2                              50913
2     3                              53291
3     4                              17032
4     5                              43634

In [41]:
merged_ng_demands = pd.merge(published_ng_feedstock_padd, sum_ref_padd, on='PADD')
merged_ng_demands

,PADD,Published NG Feedstock (MMcf/year),2022,NG eq demand 2022(MMcf/year)
0,1,6202,262690.0,14576.258121
1,2,50913,1525530.0,84649.278815
2,3,53291,1788220.0,99225.536936
3,4,17032,537430.0,29821.151936
4,5,43634,2858260.0,158600.386532